"""add is_blocked to warehouse_

Revision ID: c9ac2f0e609e
Revises: 624ceed9e148
Create Date: 2024-12-18 16:23:32.377772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ac2f0e609e'
down_revision: Union[str, None] = '624ceed9e148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'is_blocked')
    # ### end Alembic commands ###
